version: '3.8'

services:
  nginx:
    ports:
      - "${NGINX_HTTP_PORT:-8080}:80"
    volumes:
      # Mount development Nginx config
      - ./nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - puller
      - nbgrader

  puller:
    volumes:
      # Mount the source code for development
      - ./puller:/app:rw
    environment:
      # Override environment variables for development if needed
      - JUPYTER_URL=http://localhost:${NGINX_HTTP_PORT:-8080}/jupyter/


