version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    depends_on:
      - puller
      - oauth2-proxy
      - nbgrader
    networks:
      - app-network
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      # Mount Nginx config (for debug)
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  oauth2-proxy:
    build:
      context: ./oauth2-proxy
    env_file:
      - .env
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET
      - OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_GITHUB_USERS
    networks:
      - app-network
    volumes:
      # Mount config (for debug)
      - ./oauth2-proxy/oauth2-proxy.cfg:/etc/oauth2-proxy/oauth2-proxy.cfg
    restart: unless-stopped
 
  puller:
    build:
      context: ./puller
    volumes:
      - ./puller:/app
      - ./exchange:/exchange:rw
    env_file:
      - .env
    environment:
      - GITHUB_TOKEN
      - TARGET_DIR
      - REPOSITORIES_CSV_PATH
      - JUPYTER_URL
    networks:
      - app-network
    restart: unless-stopped

  nbgrader:
    build:
      context: ./nbgrader
    volumes:
      - ./nbgrader/app:/app
      - ./exchange:/usr/local/share/nbgrader/exchange
    networks:
      - app-network
    restart: unless-stopped

  nbgrader_add_students:
    build:
      context: ./nbgrader
    volumes:
      - ./nbgrader/app:/app
      - ./exchange:/usr/local/share/nbgrader/exchange
    command: "python scripts/add_students.py"
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge
